version: "3.9"
services:
  copter:
    environment:
      - MAVLINK_OUT_HOST=mavgw
    #build local images  with  "docker build -t ardupilot-sitl-docker ."
    #(don't forget to sync WSL clock with "sudo hwclock -s" in Ubuntu terminal)
    image: ardupilot-sitl-docker
  mavgw:
    image: ardupilot-sitl-docker
    container_name: mavgw
    command: ../mavp2p --hb-systemid=123 udps:0.0.0.0:14553 tcps:0.0.0.0:14554 tcps:0.0.0.0:14555
    ports:
      - "14554:14554/tcp"
      - "14555:14555/tcp"
        